version: '3'

tasks:
  init-folder:
    cmd: |
      find . -maxdepth 1 -type d -not -path . -execdir sh -c "pushd {}"; go mod init 'github.com/snirkop89/grpc-go-pro/{}'; popd" " ";"

  tidy:
    cmds:
    - cd proto && go mod tidy
    - cd client && go mod tidy
    - cd server && go mod tidy


  protoc:
    cmd: |
      protoc --go_out=. \
             --go_opt=paths=source_relative \
             --go-grpc_out=. \
             --go-grpc_opt=paths=source_relative \
             proto/todo/v1/*.proto 

  # Generate proto using buf
  # First use `buf mod init`
  buf-gen:
    cmd: buf generate proto

  bazel:
    cmd: bazel run //:gazelle


  server:
    cmd: go run ./server/ 0.0.0.0:50051

  client:
    cmd: go run ./client/ 0.0.0.0:50051

  kind-up:
    cmd: kind create cluster --config k8s/kind.yaml --name grpc

  kind-down:
    cmd: kind delete cluster --name grpc